# 数据源
spring:
  redis:
    host: 127.0.0.1
    database: 9  #避免和微服务 PIGX 冲突
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: root
#      url: jdbc:mysql://127.0.0.1:3306/tdcloudx_boot_codegen?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        username: sa
        password: tdkj@2020
        url: jdbc:sqlserver://192.168.1.135:1433;SelectMethod=cursor;DatabaseName=tdcloudx_boot_codegen;characterEncoding=utf8
  web:
    resources:
      static-locations: classpath:/static/,classpath:/views/

# 租户表维护
tdcloud:
  tenant:
    column: tenant_id
    tables:
      - gen_datasource_conf
      - gen_form_conf
