## spring security 配置
security:
  oauth2:
    client:
      ignore-urls:
        - /webjars/**
        - /v3/api-docs/**
        - /doc.html
        - /swagger-resources
        - /token/check_token
        - /error
        - /druid/**
        - /actuator/**
        - /code/**

# 前端密码登录解密密钥
gateway:
  encodeKey: pigxpigxpigxpigx

# 数据源
spring:
  redis:
    host: 127.0.0.1
    database: 9  #避免和微服务 PIGX 冲突
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: root
#      url: jdbc:mysql://127.0.0.1:3306/tdcloudx_boot?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: sa
      password: tdkj@2020
      url: jdbc:sqlserver://192.168.1.135:1433;SelectMethod=cursor;DatabaseName=tdcloudx_boot;characterEncoding=utf8
      stat-view-servlet:
        enabled: true
        allow: ""
        url-pattern: /druid/*
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 10000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

  mail:
    default-encoding: UTF-8
    host: mail.cstnet.cn
    username: message@mail.kib.ac.cn
    password: P8YmnFMv7%zPRZ4A
    port: 465
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 25000

  freemarker:
    template-loader-path: classpath:/templates
    cache: true
    checkTemplateLocation: true
    settings:
      classic_compatible: true #处理空值
      template_exception_handler: rethrow
      template_update_delay: 0
      datetime_format: yyyy-MM-dd HH:mm:ss
      number_format: 0.##
    suffix: .ftl

#  mail:
#    default-encoding: UTF-8
#    host: smtp.qq.com
#    username: 761301854@qq.com
#    password: ulistgobolevbceb
#    port: 465
#    protocol: smtp
#    properties:
#      mail:
#        smtp:
#        auth: true
#        timeout: 25000


# 本地文件系统
file:
  local:
    enable: true
    basePath: /data/file

# Logger Config
logging:
  level:
    com.tdkj.tdcloud.admin.mapper: debug

# 租户表维护
tdcloud:
  tenant:
    column: tenant_id
    tables:
      - sys_user
      - sys_role
      - sys_menu
      - sys_dept
      - sys_log
      - sys_social_details
      - sys_dict
      - sys_dict_item
      - sys_public_param
      - sys_log
      - sys_file
      - sys_oauth_client_details
      - sys_post

